# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:11:47+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Path, Query
from pydantic import conint

from models import Error, ErrorLimit, Order, OrderList, Sort

app = MCPProxy(
    title='',
    version='1.0.0',
    servers=[{'url': '//api.ote-godaddy.com'}],
)


@app.get(
    '/v1/orders',
    description=""" <strong>API Resellers</strong><ul><li>This endpoint does not support subaccounts and therefore API Resellers should not supply an X-Shopper-Id header</li></ul> """,
    tags=['order_management'],
)
def list(
    period_start: Optional[str] = Query(None, alias='periodStart'),
    period_end: Optional[str] = Query(None, alias='periodEnd'),
    domain: Optional[str] = None,
    product_group_id: Optional[int] = Query(None, alias='productGroupId'),
    payment_profile_id: Optional[int] = Query(None, alias='paymentProfileId'),
    parent_order_id: Optional[str] = Query(None, alias='parentOrderId'),
    offset: Optional[int] = 0,
    limit: Optional[conint(ge=1, le=10000)] = 25,
    sort: Optional[Sort] = '-createdAt',
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    x__market__id: Optional[str] = Header('en-US', alias='X-Market-Id'),
):
    """
    Retrieve a list of orders for the authenticated shopper. Only one filter may be used at a time
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/orders/{orderId}',
    description=""" <strong>API Resellers</strong><ul><li>This endpoint does not support subaccounts and therefore API Resellers should not supply an X-Shopper-Id header</li></ul> """,
    tags=['order_management'],
)
def get(
    order_id: str = Path(..., alias='orderId'),
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    x__market__id: Optional[str] = Header('en-US', alias='X-Market-Id'),
):
    """
    Retrieve details for specified order
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
